// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// eigenCpp
List eigenCpp(Eigen::Map<Eigen::MatrixXd> X);
RcppExport SEXP iprior_eigenCpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    __result = Rcpp::wrap(eigenCpp(X));
    return __result;
END_RCPP
}
// fastSquare
Eigen::MatrixXd fastSquare(SEXP X);
RcppExport SEXP iprior_fastSquare(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    __result = Rcpp::wrap(fastSquare(X));
    return __result;
END_RCPP
}
// fastVDiag
NumericMatrix fastVDiag(NumericMatrix X, NumericVector y);
RcppExport SEXP iprior_fastVDiag(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    __result = Rcpp::wrap(fastVDiag(X, y));
    return __result;
END_RCPP
}
