# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Eigen decomposition of a matrix in C++
#'
#' Returns the eigenvalues and eigenvectors of a matrix \code{M}.
#'
#' @param M A symmetric, positive-definite matrix
#'
#'
#' @details A fast implementation of \code{eigen()} for symmetric,
#' positive-definite matrices. This helps speed up the I-prior EM algorithm.
#' @export
EigenCpp <- function(M) {
    .Call('iprior_EigenCpp', PACKAGE = 'iprior', M)
}

#' Multiplying a symmetric matrix by itself in C++
#'
#' Returns the square of a symmetric matrix \code{AA}.
#'
#' @param AA A symmetric matrix
#'
#'
#' @details A fast implementation of \code{AA %*% AA} for symmetric
#' matrices. This helps speed up the I-prior EM algorithm.
#' @export
FastSquare <- function(AA) {
    .Call('iprior_FastSquare', PACKAGE = 'iprior', AA)
}

#' Computing a quadratic matrix form in C++
#'
#' Returns \code{X %*% diag(y) %*% t(X)}
#'
#' @param X A symmetric, square matrix of dimension \code{n} by \code{n}
#' @param y A vector of length \code{n}
#'
#' @details A fast implementation of \code{X %*% diag(y) %*% t(X)}. This helps
#'   speed up the I-prior EM algorithm.
#' @export
FastVdiag <- function(X, y) {
    .Call('iprior_FastVdiag', PACKAGE = 'iprior', X, y)
}

