# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenCpp <- function(X) {
    .Call('iprior_eigenCpp', PACKAGE = 'iprior', X)
}

fastSquare <- function(X) {
    .Call('iprior_fastSquare', PACKAGE = 'iprior', X)
}

fastVDiag <- function(X, y) {
    .Call('iprior_fastVDiag', PACKAGE = 'iprior', X, y)
}

